/* eslint-disable */
/**
 * Generated by scripts/generate_local_api_openapi_types.py.
 * Do not edit by hand.
 */

export type LocalApiJsonValue =
  | string
  | number
  | boolean
  | null
  | LocalApiJsonValue[]
  | { [key: string]: LocalApiJsonValue };

export type LocalApiSchemas = {
  RunSpecRequest: {
    pipelineId: string;
    projectId?: string | null;
    pipelineVersion?: string | null;
    runId?: string | null;
    runSpecVersion?: string | null;
    workflowRevisionId?: string | null;
    inputs?: Record<string, LocalApiJsonValue>[] | null;
    params?: Record<string, LocalApiJsonValue> | null;
    resourceBindings?: Record<string, LocalApiJsonValue> | null;
    sampleDataPrepProof?: Record<string, LocalApiJsonValue> | null;
    execution?: Record<string, LocalApiJsonValue> | null;
    workflowDesign?: Record<string, LocalApiJsonValue> | null;
    workflow?: Record<string, LocalApiJsonValue> | null;
  };
  RunSubmitRequest: {
    serverId: string;
    runId?: string | null;
    requestId?: string | null;
    idempotencyKey?: string | null;
    runSpec: LocalApiSchemas["RunSpecRequest"];
  };
  WorkflowDesignDraftCompileRequest: {
    serverId?: string | null;
  };
  WorkflowDesignDraftCreateRequest: {
    serverId?: string | null;
    draft: LocalApiSchemas["WorkflowDesignDraftV1"];
  };
  WorkflowDesignDraftForkRequest: {
    serverId?: string | null;
    name?: string | null;
  };
  WorkflowDesignDraftPlanRequest: {
    serverId?: string | null;
    proposedEdges?: LocalApiSchemas["WorkflowDesignEdge"][];
  };
  WorkflowDesignDraftUpdateRequest: {
    serverId?: string | null;
    draft: LocalApiSchemas["WorkflowDesignDraftV1"];
    expectedRevision?: number | null;
  };
  WorkflowDesignDraftV1: {
    contractVersion: "workflow-design-draft-v1";
    engine: "snakemake";
    metadata: LocalApiSchemas["WorkflowDesignMetadata"];
    inputs?: LocalApiSchemas["WorkflowDesignInput"][];
    nodes?: LocalApiSchemas["WorkflowDesignNode"][];
    edges?: LocalApiSchemas["WorkflowDesignEdge"][];
    resources?: LocalApiSchemas["WorkflowDesignResources"];
    outputs?: LocalApiSchemas["WorkflowDesignOutput"][];
    provenance?: Record<string, string | number | boolean>;
  };
  WorkflowDesignEdge: {
    id?: string | null;
    from: LocalApiSchemas["WorkflowDesignPortRef"];
    to: LocalApiSchemas["WorkflowDesignPortRef"];
    audit?: Record<string, string | number | boolean> | null;
  };
  WorkflowDesignInput: {
    id: string;
    role: string;
    path: string;
    filename?: string | null;
    type?: string;
    kind?: string;
    mimeType?: string;
    data?: string;
    format?: string;
    operation?: string;
    resource?: string;
    metadata?: Record<string, string | number | boolean>;
  };
  WorkflowDesignInputBindingFromInput: {
    fromInput: string;
  };
  WorkflowDesignMetadata: {
    name: string;
    description?: string;
    projectId?: string;
    tags?: string[];
  };
  WorkflowDesignNode: {
    id: string;
    toolRevisionId: string;
    inputs?: Record<string, LocalApiSchemas["WorkflowDesignInputBindingFromInput"]>;
    params?: Record<string, string | number | boolean>;
    runtime?: LocalApiSchemas["WorkflowDesignRuntime"];
    resources?: Record<string, string | number | boolean>;
    outputs?: Record<string, LocalApiSchemas["WorkflowDesignNodeOutput"]>;
    metadata?: Record<string, string | number | boolean>;
    provenance?: Record<string, string | number | boolean>;
  };
  WorkflowDesignNodeOutput: {
    expose?: boolean;
    alias?: string | null;
    metadata?: Record<string, string | number | boolean>;
  };
  WorkflowDesignOutput: {
    from: LocalApiSchemas["WorkflowDesignPortRef"];
    as: string;
    metadata?: Record<string, string | number | boolean>;
  };
  WorkflowDesignPortRef: {
    nodeId: string;
    port: string;
  };
  WorkflowDesignResources: {
    bindings?: Record<string, Record<string, string>>;
    metadata?: Record<string, string | number | boolean>;
  };
  WorkflowDesignRuntime: {
    threads?: number | null;
    resources?: Record<string, string | number | boolean>;
    schedulerResources?: Record<string, string | number | boolean>;
    log?: string | Record<string, string> | null;
  };
};

export type LocalApiRunSpecRequest = LocalApiSchemas["RunSpecRequest"];
export type LocalApiRunSubmitRequest = LocalApiSchemas["RunSubmitRequest"];
export type LocalApiWorkflowDesignDraftCreateRequest = LocalApiSchemas["WorkflowDesignDraftCreateRequest"];
export type LocalApiWorkflowDesignDraftUpdateRequest = LocalApiSchemas["WorkflowDesignDraftUpdateRequest"];
export type LocalApiWorkflowDesignDraftPlanRequest = LocalApiSchemas["WorkflowDesignDraftPlanRequest"];
export type LocalApiWorkflowDesignDraftCompileRequest = LocalApiSchemas["WorkflowDesignDraftCompileRequest"];
export type LocalApiWorkflowDesignDraftForkRequest = LocalApiSchemas["WorkflowDesignDraftForkRequest"];
