from __future__ import annotations


TOOL_PRODUCTION_CONFLICT_DETAILS = {
    "TOOL_PRODUCTION_REQUIRES_OUTPUT_VALIDATION",
    "TOOL_PRODUCTION_REQUIRES_WORKFLOW_READY",
    "TOOL_PRODUCTION_EVIDENCE_RUN_NOT_FOUND",
    "TOOL_PRODUCTION_EVIDENCE_RUN_NOT_COMPLETED",
    "TOOL_PRODUCTION_EVIDENCE_PIPELINE_MISMATCH",
    "TOOL_PRODUCTION_EVIDENCE_TOOL_MISMATCH",
    "TOOL_PRODUCTION_EVIDENCE_ARTIFACT_REQUIRED",
    "TOOL_PRODUCTION_EVIDENCE_ARTIFACT_NOT_FOUND",
    "TOOL_PRODUCTION_EVIDENCE_ARTIFACT_EMPTY",
    "TOOL_PRODUCTION_EVIDENCE_DATABASE_MISMATCH",
    "TOOL_PRODUCTION_EVIDENCE_DATABASE_UNAVAILABLE",
}


def tool_production_status_code(detail: str) -> int:
    if detail == "TOOL_NOT_FOUND":
        return 404
    if detail in TOOL_PRODUCTION_CONFLICT_DETAILS:
        return 409
    return 400
