from __future__ import annotations


WAITING_RESOURCE_CODES = {
    "RESOURCE_BINDING_MISSING",
    "RESOURCE_BINDING_AMBIGUOUS",
    "WORKFLOW_RESOURCE_BINDING_REQUIRED",
    "WORKFLOW_RESOURCE_UNAVAILABLE",
}
