from __future__ import annotations

import re
import uuid
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


PROBLEM_DETAIL_MEDIA_TYPE = "application/problem+json"
PROBLEM_TYPE_BASE_URI = "https://h2ometa.dev/problems"
DEFAULT_PROBLEM_STATUS_CODES = (400, 401, 403, 404, 409, 413, 422, 500, 502, 503)


class ProblemDetail(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: str = Field(description="A URI identifying the problem type.")
    title: str = Field(description="A short, human-readable summary of the problem type.")
    status: int = Field(description="The HTTP status code generated by the server.")
    detail: str = Field(description="A human-readable explanation specific to this occurrence.")
    instance: str = Field(description="A URI reference identifying this occurrence.")
    code: str = Field(description="Stable H2OMeta problem code.")
    requestId: str = Field(description="Request correlation identifier.")
    errors: list[dict[str, Any]] | None = Field(default=None, description="Field or validation errors.")


def ensure_request_id(value: str | None = None) -> str:
    candidate = str(value or "").strip()
    return candidate or f"req_{uuid.uuid4().hex[:8]}"


def problem_type_uri(code: str) -> str:
    normalized = normalize_problem_code(code).lower().replace("_", "-")
    return f"{PROBLEM_TYPE_BASE_URI}/{normalized}"


def normalize_problem_code(value: Any, *, default: str = "H2OMETA_ERROR") -> str:
    def normalize_token(token: str) -> str:
        return token.upper().replace("-", "_").replace(".", "_")

    candidate = str(value or "").strip()
    fallback = normalize_token(str(default or "H2OMETA_ERROR").strip() or "H2OMETA_ERROR")
    if not candidate:
        return fallback
    token = candidate.split(":", 1)[0].strip()
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_.-]{0,127}", token):
        return fallback
    return normalize_token(token)


def build_problem_detail(
    *,
    status: int,
    title: str,
    detail: str,
    code: str,
    request_id: str,
    instance: str,
    errors: list[dict[str, Any]] | None = None,
    extensions: dict[str, Any] | None = None,
) -> dict[str, Any]:
    normalized_code = normalize_problem_code(code)
    payload: dict[str, Any] = {
        "type": problem_type_uri(normalized_code),
        "title": str(title or "Request failed"),
        "status": int(status),
        "detail": str(detail or normalized_code),
        "instance": str(instance or ""),
        "code": normalized_code,
        "requestId": ensure_request_id(request_id),
    }
    if errors:
        payload["errors"] = errors
    if extensions:
        for key, value in extensions.items():
            if key not in payload:
                payload[key] = value
    return payload


def problem_detail_response(status_code: int) -> dict[str, Any]:
    return {
        "description": f"RFC 9457 Problem Details ({int(status_code)})",
        "content": {
            PROBLEM_DETAIL_MEDIA_TYPE: {
                "schema": {"$ref": "#/components/schemas/ProblemDetail"},
            },
        },
    }


def problem_detail_responses(
    status_codes: tuple[int, ...] = DEFAULT_PROBLEM_STATUS_CODES,
) -> dict[int, dict[str, Any]]:
    return {
        int(status_code): problem_detail_response(int(status_code))
        for status_code in status_codes
    }


def install_problem_details_openapi(app: Any) -> None:
    original_openapi = app.openapi

    def openapi_with_problem_details() -> dict[str, Any]:
        if app.openapi_schema:
            return app.openapi_schema
        schema = original_openapi()
        schema.setdefault("components", {}).setdefault("schemas", {})[
            "ProblemDetail"
        ] = ProblemDetail.model_json_schema(
            ref_template="#/components/schemas/{model}"
        )
        app.openapi_schema = schema
        return app.openapi_schema

    app.openapi = openapi_with_problem_details


def problem_extensions_from_payload(payload: Any) -> dict[str, Any]:
    if not isinstance(payload, dict):
        return {}
    return {
        str(key): value
        for key, value in payload.items()
        if str(key) not in {"type", "title", "status", "detail", "instance", "requestId"}
    }
