"""Machine-readable governance policy for high-risk API actions."""

from __future__ import annotations

from dataclasses import dataclass


SUPPORTED_BOUNDARIES = {"desktop-localhost-only", "remote-runner-bearer-token"}
SUPPORTED_AUDIT_STATUS = {"implemented", "required-before-multi-user"}
SUPPORTED_ROLES = {
    "artifact-curator",
    "auditor",
    "data-steward",
    "platform-admin",
    "tool-curator",
    "workflow-operator",
}
SECRET_DETAIL_KEY_PARTS = (
    "api_key",
    "apikey",
    "authorization",
    "bearer",
    "key",
    "password",
    "private",
    "secret",
    "token",
)


@dataclass(frozen=True)
class ApiGovernancePolicy:
    surface: str
    method: str
    route: str
    route_source: str
    action: str
    subject_kind: str
    current_boundary: str
    future_roles: tuple[str, ...]
    audit_status: str
    standards: tuple[str, ...]
    safe_detail_keys: tuple[str, ...] = ()
    multi_user_ready: bool = False

    @property
    def key(self) -> str:
        return f"{self.surface}:{self.method}:{self.route}"


def local_policy(method: str, route: str, action: str, subject_kind: str, *roles: str) -> ApiGovernancePolicy:
    return ApiGovernancePolicy(
        surface="local-api",
        method=method,
        route=route,
        route_source="apps/api/ssh_routes.py",
        action=action,
        subject_kind=subject_kind,
        current_boundary="desktop-localhost-only",
        future_roles=tuple(roles),
        audit_status="required-before-multi-user",
        standards=("OWASP-ASVS-5", "OWASP-Logging"),
        safe_detail_keys=("serverId", "requestId", "outcome"),
    )


def remote_policy(
    method: str,
    route: str,
    source: str,
    action: str,
    subject_kind: str,
    audit_status: str,
    *roles: str,
) -> ApiGovernancePolicy:
    return ApiGovernancePolicy(
        surface="remote-runner-api",
        method=method,
        route=route,
        route_source=source,
        action=action,
        subject_kind=subject_kind,
        current_boundary="remote-runner-bearer-token",
        future_roles=tuple(roles),
        audit_status=audit_status,
        standards=("OWASP-ASVS-5", "OWASP-Logging"),
        safe_detail_keys=("serverId", "requestId", "actor", "decision", "reasonCode"),
    )


HIGH_RISK_API_POLICIES: tuple[ApiGovernancePolicy, ...] = (
    local_policy("POST", "/api/v1/ssh/connect", "ssh.connect", "server", "platform-admin"),
    local_policy("POST", "/api/v1/ssh/test", "ssh.test", "server", "platform-admin"),
    local_policy("POST", "/api/v1/ssh/remote-service/stop", "remote_runner.stop", "server", "platform-admin"),
    local_policy("POST", "/api/v1/servers/{server_id}/ensure-runner", "remote_runner.ensure", "server", "platform-admin"),
    local_policy("POST", "/api/v1/servers/{server_id}/host-key/accept", "ssh.host_key.accept", "server", "platform-admin"),
    local_policy("POST", "/api/v1/servers/{server_id}/token/rotate", "remote_runner.token.rotate", "server", "platform-admin"),
    local_policy("GET", "/api/v1/servers/{server_id}/operator-diagnostics", "diagnostics.operator.read", "server", "auditor"),
    local_policy("GET", "/api/v1/ssh/files", "remote_file.list", "server", "workflow-operator", "auditor"),
    local_policy("POST", "/api/v1/ssh/terminal/sessions", "ssh.terminal.create", "server", "platform-admin"),
    local_policy("WEBSOCKET", "/api/v1/ssh/terminal/sessions/{session_id}/stream", "ssh.terminal.stream", "server", "platform-admin"),
    remote_policy(
        "POST",
        "/api/v1/runs",
        "apps/remote_runner/submission_routes.py",
        "run.submit",
        "run",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/cancel",
        "apps/remote_runner/execution_query_routes.py",
        "run.cancel",
        "run",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/retry",
        "apps/remote_runner/execution_query_routes.py",
        "run.retry",
        "run",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/rules/retry",
        "apps/remote_runner/execution_query_routes.py",
        "run.rule_retry",
        "run_rule_retry",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/rules/output-invalidation/apply",
        "apps/remote_runner/execution_query_routes.py",
        "run.rule_output_invalidation.apply",
        "run_rule_output_invalidation",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/rules/cache-restore/pins/prepare",
        "apps/remote_runner/execution_query_routes.py",
        "run.rule_cache_restore.pins.prepare",
        "run_rule_cache_restore_pins",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/rules/cache-restore/pins/apply",
        "apps/remote_runner/execution_query_routes.py",
        "run.rule_cache_restore.pins.apply",
        "run_rule_cache_restore_pins",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/rules/cache-restore/staged-files/prepare",
        "apps/remote_runner/execution_query_routes.py",
        "run.rule_cache_restore.staged_files.prepare",
        "run_rule_cache_restore_staged_files",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/rules/cache-restore/staged-files/apply",
        "apps/remote_runner/execution_query_routes.py",
        "run.rule_cache_restore.staged_files.apply",
        "run_rule_cache_restore_staged_files",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/rules/cache-restore/final-outputs/prepare",
        "apps/remote_runner/execution_query_routes.py",
        "run.rule_cache_restore.final_outputs.prepare",
        "run_rule_cache_restore_final_outputs",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/rules/cache-restore/final-outputs/apply",
        "apps/remote_runner/execution_query_routes.py",
        "run.rule_cache_restore.final_outputs.apply",
        "run_rule_cache_restore_final_outputs",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/rules/cache-restore/adoption/prepare",
        "apps/remote_runner/execution_query_routes.py",
        "run.rule_cache_restore.adoption.prepare",
        "run_rule_cache_restore_adoption",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/rules/cache-restore/adoption/apply",
        "apps/remote_runner/execution_query_routes.py",
        "run.rule_cache_restore.adoption.apply",
        "run_rule_cache_restore_adoption",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/runs/{run_id}/resume",
        "apps/remote_runner/execution_query_routes.py",
        "run.resume",
        "run_resume",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "GET",
        "/api/v1/runs/{run_id}/events",
        "apps/remote_runner/execution_query_routes.py",
        "run.events.read",
        "run_events",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/runs/{run_id}/execution-context",
        "apps/remote_runner/execution_query_routes.py",
        "run.execution_context.read",
        "run_execution_context",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/runs/{run_id}/attempts",
        "apps/remote_runner/execution_query_routes.py",
        "run.attempts.read",
        "run_attempts",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/runs/{run_id}/logs",
        "apps/remote_runner/execution_query_routes.py",
        "run.logs.read",
        "run_logs",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/runs/{run_id}/rules",
        "apps/remote_runner/execution_query_routes.py",
        "run.rules.read",
        "run_rules",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/runs/{run_id}/failure-locator",
        "apps/remote_runner/execution_query_routes.py",
        "run.failure_locator.read",
        "run_failure_locator",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/runs/{run_id}/results",
        "apps/remote_runner/execution_query_routes.py",
        "run.results.read",
        "run_results",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/results",
        "apps/remote_runner/execution_query_routes.py",
        "result.list",
        "result",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/results/{result_id}",
        "apps/remote_runner/execution_query_routes.py",
        "result.read",
        "result",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/results/{result_id}/export",
        "apps/remote_runner/execution_query_routes.py",
        "result.export",
        "result",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/results/{result_id}/preview",
        "apps/remote_runner/execution_query_routes.py",
        "result.artifact.preview",
        "result_artifact",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/results/{result_id}/audit",
        "apps/remote_runner/execution_query_routes.py",
        "result.artifact_audit.read",
        "result_artifact_audit",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/results/{result_id}/exports",
        "apps/remote_runner/execution_query_routes.py",
        "result.package.list",
        "result_package_export",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/result-package-exports/bytes/gc/preview",
        "apps/remote_runner/execution_query_routes.py",
        "result.package.bytes.preview",
        "result_package_export",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/result-package-exports/bytes/gc/run",
        "apps/remote_runner/execution_query_routes.py",
        "result.package.bytes.run",
        "result_package_export",
        "implemented",
        "artifact-curator",
    ),
    remote_policy(
        "GET",
        "/api/v1/results/{result_id}/exports/{package_export_id}/download",
        "apps/remote_runner/execution_query_routes.py",
        "result.package.download",
        "result_package_export",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/results/{result_id}/exports/{package_export_id}/retire",
        "apps/remote_runner/execution_query_routes.py",
        "result.package.retire",
        "result_package_export",
        "implemented",
        "artifact-curator",
    ),
    remote_policy(
        "GET",
        "/api/v1/audit/events",
        "apps/remote_runner/audit_routes.py",
        "audit.events.read",
        "governance_audit",
        "implemented",
        "auditor",
        "platform-admin",
    ),
    remote_policy(
        "GET",
        "/api/v1/secrets/provider-readiness",
        "apps/remote_runner/secret_routes.py",
        "secret.provider_readiness.read",
        "secret_provider",
        "implemented",
        "auditor",
        "platform-admin",
    ),
    remote_policy(
        "POST",
        "/api/v1/artifacts/lifecycle/gc/preview",
        "apps/remote_runner/execution_query_routes.py",
        "artifact.gc.preview",
        "artifact_gc",
        "implemented",
        "artifact-curator",
    ),
    remote_policy(
        "GET",
        "/api/v1/artifacts/lifecycle/usage",
        "apps/remote_runner/execution_query_routes.py",
        "artifact.lifecycle.usage.read",
        "artifact_lifecycle_usage",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/artifacts/lifecycle/controller/ticks",
        "apps/remote_runner/execution_query_routes.py",
        "artifact.lifecycle.controller_ticks.read",
        "artifact_lifecycle_controller",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/artifacts/lifecycle/controller/run-once",
        "apps/remote_runner/execution_query_routes.py",
        "artifact.lifecycle.controller.run_once",
        "artifact_lifecycle_controller",
        "implemented",
        "artifact-curator",
    ),
    remote_policy(
        "POST",
        "/api/v1/artifacts/lifecycle/gc/run",
        "apps/remote_runner/execution_query_routes.py",
        "artifact.gc.run",
        "artifact_gc",
        "implemented",
        "artifact-curator",
    ),
    remote_policy(
        "GET",
        "/api/v1/artifacts/cache/entries",
        "apps/remote_runner/execution_query_routes.py",
        "artifact.cache.entries.read",
        "artifact_cache",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/artifacts/cache/pins",
        "apps/remote_runner/execution_query_routes.py",
        "artifact.cache_pins.read",
        "artifact_cache_pin",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/artifacts/cache/lookup",
        "apps/remote_runner/execution_query_routes.py",
        "artifact.cache.lookup",
        "artifact_cache",
        "implemented",
        "artifact-curator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/artifacts/cache/entries/{cache_entry_id}/retain",
        "apps/remote_runner/execution_query_routes.py",
        "artifact.cache_pin.retain",
        "artifact_cache",
        "implemented",
        "artifact-curator",
    ),
    remote_policy(
        "POST",
        "/api/v1/artifacts/cache/pins/{cache_pin_id}/release",
        "apps/remote_runner/execution_query_routes.py",
        "artifact.cache_pin.release",
        "artifact_cache_pin",
        "implemented",
        "artifact-curator",
    ),
    remote_policy(
        "GET",
        "/api/v1/workflow-triggers",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.list",
        "workflow_trigger",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/workflow-triggers",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.create",
        "workflow_trigger",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "GET",
        "/api/v1/workflow-triggers/{trigger_id}/events",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.events.read",
        "workflow_trigger_event",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/workflow-triggers/{trigger_id}/events",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.dispatch",
        "workflow_trigger_event",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "GET",
        "/api/v1/workflow-triggers/{trigger_id}/inbox",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.inbox.read",
        "workflow_trigger_inbox_event",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/workflow-trigger-scheduler/ticks",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.scheduler_ticks.read",
        "workflow_trigger_scheduler",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/workflow-trigger-scheduler/run-once",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.scheduler.run_once",
        "workflow_trigger_scheduler",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/workflow-triggers/{trigger_id}/inbox",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.dispatch",
        "workflow_trigger_event",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/workflow-triggers/{trigger_id}/inbox/{inbox_event_id}/replay",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.inbox_replay",
        "workflow_trigger_inbox_event",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "GET",
        "/api/v1/workflow-triggers/{trigger_id}/readiness-observation",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.readiness_observation.read",
        "workflow_trigger_readiness_observation",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/workflow-triggers/{trigger_id}/readiness",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.dispatch",
        "workflow_trigger_event",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/workflow-triggers/{trigger_id}/backfill/preview",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.backfill_preview",
        "workflow_trigger",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/workflow-triggers/{trigger_id}/backfill/launch",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.backfill_launch",
        "workflow_backfill_launch",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "GET",
        "/api/v1/workflow-backfill-launches",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.backfill_launch.list",
        "workflow_backfill_launch",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "GET",
        "/api/v1/workflow-backfill-launches/{launch_id}",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.backfill_launch.read",
        "workflow_backfill_launch",
        "implemented",
        "workflow-operator",
        "auditor",
    ),
    remote_policy(
        "POST",
        "/api/v1/workflow-backfill-launches/{launch_id}/cancel",
        "apps/remote_runner/workflow_trigger_routes.py",
        "workflow_trigger.backfill_cancel",
        "workflow_backfill_launch",
        "implemented",
        "workflow-operator",
    ),
    remote_policy(
        "POST",
        "/api/v1/tools",
        "apps/remote_runner/tool_routes.py",
        "tool.create",
        "tool",
        "implemented",
        "tool-curator",
    ),
    remote_policy(
        "POST",
        "/api/v1/tools/prepare-jobs",
        "apps/remote_runner/tool_routes.py",
        "tool.prepare",
        "tool_prepare_job",
        "implemented",
        "tool-curator",
    ),
    remote_policy(
        "POST",
        "/api/v1/tools/prepare-jobs/{job_id}/cancel",
        "apps/remote_runner/tool_routes.py",
        "tool.prepare.cancel",
        "tool_prepare_job",
        "implemented",
        "tool-curator",
    ),
    remote_policy(
        "PATCH",
        "/api/v1/tools/{tool_id}/rule-template",
        "apps/remote_runner/tool_routes.py",
        "tool.rule_template.update",
        "tool",
        "implemented",
        "tool-curator",
        "platform-admin",
    ),
    remote_policy(
        "POST",
        "/api/v1/tools/{tool_id}/production",
        "apps/remote_runner/tool_routes.py",
        "tool.production.enable",
        "tool",
        "implemented",
        "tool-curator",
        "platform-admin",
    ),
    remote_policy(
        "DELETE",
        "/api/v1/tools/{tool_id}",
        "apps/remote_runner/tool_routes.py",
        "tool.delete",
        "tool",
        "implemented",
        "tool-curator",
        "platform-admin",
    ),
    remote_policy(
        "POST",
        "/api/v1/databases",
        "apps/remote_runner/database_routes.py",
        "database.create",
        "database",
        "implemented",
        "data-steward",
    ),
    remote_policy(
        "PATCH",
        "/api/v1/databases/{database_id}",
        "apps/remote_runner/database_routes.py",
        "database.update",
        "database",
        "implemented",
        "data-steward",
    ),
    remote_policy(
        "POST",
        "/api/v1/databases/{database_id}/check",
        "apps/remote_runner/database_routes.py",
        "database.check",
        "database",
        "implemented",
        "data-steward",
    ),
    remote_policy(
        "DELETE",
        "/api/v1/databases/{database_id}",
        "apps/remote_runner/database_routes.py",
        "database.delete",
        "database",
        "implemented",
        "data-steward",
        "platform-admin",
    ),
)


def validate_governance_policy(policies: tuple[ApiGovernancePolicy, ...] = HIGH_RISK_API_POLICIES) -> list[str]:
    errors: list[str] = []
    seen_keys: set[str] = set()
    for policy in policies:
        if policy.key in seen_keys:
            errors.append(f"duplicate policy key: {policy.key}")
        seen_keys.add(policy.key)
        if policy.current_boundary not in SUPPORTED_BOUNDARIES:
            errors.append(f"{policy.key} has unsupported boundary: {policy.current_boundary}")
        if policy.audit_status not in SUPPORTED_AUDIT_STATUS:
            errors.append(f"{policy.key} has unsupported audit status: {policy.audit_status}")
        if not policy.future_roles:
            errors.append(f"{policy.key} must declare future RBAC roles")
        for role in policy.future_roles:
            if role not in SUPPORTED_ROLES:
                errors.append(f"{policy.key} has unsupported future role: {role}")
        if policy.multi_user_ready:
            errors.append(f"{policy.key} must stay blocked until auth/RBAC enforcement exists")
        for key in policy.safe_detail_keys:
            normalized = key.lower().replace("-", "_")
            if any(part in normalized for part in SECRET_DETAIL_KEY_PARTS):
                errors.append(f"{policy.key} declares secret-like audit detail key: {key}")
    return errors
