from __future__ import annotations

from pathlib import Path
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from apps.api.main import app

OUTPUT_PATH = ROOT / "apps" / "web" / "app" / "lib" / "local-api-openapi-types.ts"

ROOT_SCHEMA_NAMES = (
    "RunSpecRequest",
    "RunSubmitRequest",
    "WorkflowDesignDraftCreateRequest",
    "WorkflowDesignDraftUpdateRequest",
    "WorkflowDesignDraftPlanRequest",
    "WorkflowDesignDraftCompileRequest",
    "WorkflowDesignDraftForkRequest",
)

EXPORTED_ALIASES = {
    "RunSpecRequest": "LocalApiRunSpecRequest",
    "RunSubmitRequest": "LocalApiRunSubmitRequest",
    "WorkflowDesignDraftCreateRequest": "LocalApiWorkflowDesignDraftCreateRequest",
    "WorkflowDesignDraftUpdateRequest": "LocalApiWorkflowDesignDraftUpdateRequest",
    "WorkflowDesignDraftPlanRequest": "LocalApiWorkflowDesignDraftPlanRequest",
    "WorkflowDesignDraftCompileRequest": "LocalApiWorkflowDesignDraftCompileRequest",
    "WorkflowDesignDraftForkRequest": "LocalApiWorkflowDesignDraftForkRequest",
}


def main() -> None:
    OUTPUT_PATH.write_text(generate_types(), encoding="utf-8")


def generate_types() -> str:
    schemas = app.openapi()["components"]["schemas"]
    selected = _collect_schema_names(schemas)
    lines = [
        "/* eslint-disable */",
        "/**",
        " * Generated by scripts/generate_local_api_openapi_types.py.",
        " * Do not edit by hand.",
        " */",
        "",
        "export type LocalApiJsonValue =",
        "  | string",
        "  | number",
        "  | boolean",
        "  | null",
        "  | LocalApiJsonValue[]",
        "  | { [key: string]: LocalApiJsonValue };",
        "",
        "export type LocalApiSchemas = {",
    ]
    for name in selected:
        lines.append(f"  {name}: {_schema_to_ts(schemas[name], schemas, indent=2)};")
    lines.append("};")
    lines.append("")
    for schema_name, alias in EXPORTED_ALIASES.items():
        lines.append(f'export type {alias} = LocalApiSchemas["{schema_name}"];')
    lines.append("")
    return "\n".join(lines)


def _collect_schema_names(schemas: dict[str, Any]) -> list[str]:
    selected: set[str] = set()
    pending = list(ROOT_SCHEMA_NAMES)
    while pending:
        name = pending.pop()
        if name in selected:
            continue
        if name not in schemas:
            raise KeyError(f"OpenAPI schema not found: {name}")
        selected.add(name)
        pending.extend(ref for ref in _schema_refs(schemas[name]) if ref not in selected)
    return sorted(selected)


def _schema_refs(schema: Any) -> set[str]:
    refs: set[str] = set()
    if isinstance(schema, dict):
        ref = schema.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
            refs.add(ref.rsplit("/", 1)[1])
        for value in schema.values():
            refs.update(_schema_refs(value))
    elif isinstance(schema, list):
        for item in schema:
            refs.update(_schema_refs(item))
    return refs


def _schema_to_ts(schema: dict[str, Any], schemas: dict[str, Any], *, indent: int) -> str:
    ref = schema.get("$ref")
    if isinstance(ref, str):
        return f'LocalApiSchemas["{ref.rsplit("/", 1)[1]}"]'
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema and isinstance(schema["enum"], list):
        return " | ".join(_literal(item) for item in schema["enum"])
    if "anyOf" in schema:
        return _union(schema["anyOf"], schemas, indent=indent)
    if "oneOf" in schema:
        return _union(schema["oneOf"], schemas, indent=indent)

    schema_type = schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"{_schema_to_ts(schema.get('items') or {}, schemas, indent=indent)}[]"
    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        return _object_to_ts(schema, schemas, indent=indent)
    return "unknown"


def _union(items: list[dict[str, Any]], schemas: dict[str, Any], *, indent: int) -> str:
    values = [_schema_to_ts(item, schemas, indent=indent) for item in items]
    unique = list(dict.fromkeys(values))
    return " | ".join(unique)


def _object_to_ts(schema: dict[str, Any], schemas: dict[str, Any], *, indent: int) -> str:
    properties = schema.get("properties") if isinstance(schema.get("properties"), dict) else {}
    required = set(schema.get("required") or [])
    additional = schema.get("additionalProperties", False)
    pad = " " * indent
    child_pad = " " * (indent + 2)
    if not properties:
        if additional is True:
            return "Record<string, LocalApiJsonValue>"
        if isinstance(additional, dict):
            return f"Record<string, {_schema_to_ts(additional, schemas, indent=indent)}>"
        return "Record<string, never>"

    lines = ["{"]
    for key, value in properties.items():
        optional = "" if key in required else "?"
        lines.append(f"{child_pad}{_property_name(key)}{optional}: {_schema_to_ts(value, schemas, indent=indent + 2)};")
    if additional is True:
        lines.append(f"{child_pad}[key: string]: LocalApiJsonValue;")
    elif isinstance(additional, dict):
        lines.append(f"{child_pad}[key: string]: {_schema_to_ts(additional, schemas, indent=indent + 2)};")
    lines.append(f"{pad}}}")
    return "\n".join(lines)


def _property_name(key: str) -> str:
    return key if key.isidentifier() else _literal(key)


def _literal(value: Any) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


if __name__ == "__main__":
    main()
