export type WorkflowRunTriggerProvenance = {
  schemaVersion?: string;
  available?: boolean;
  reasonCode?: string;
  runId?: string;
  triggerId?: string;
  triggerEventId?: string;
  source?: string;
  cursor?: string;
  trigger?: {
    triggerId?: string;
    name?: string;
    sourceType?: string;
    serverId?: string;
    pipelineId?: string;
    enabled?: boolean;
    createdAt?: string;
    updatedAt?: string;
  };
  event?: {
    triggerEventId?: string;
    triggerId?: string;
    sourceType?: string;
    eventType?: string;
    externalEventId?: string;
    idempotencyKey?: string;
    payloadHash?: string;
    cursor?: string;
    createdAt?: string;
  };
  dispatch?: {
    dispatchId?: string;
    triggerEventId?: string;
    triggerId?: string;
    state?: string;
    runId?: string;
    requestId?: string;
    idempotencyKey?: string;
    errorHash?: string;
    createdAt?: string;
    updatedAt?: string;
  };
  backfillPartition?: {
    partitionId?: string;
    launchId?: string;
    triggerId?: string;
    partitionKey?: string;
    index?: number;
    window?: {
      start?: string;
      end?: string;
      semantics?: string;
    };
    cursor?: string;
    idempotencyKey?: string;
    triggerEventId?: string;
    runId?: string;
    state?: string;
    runSpecHash?: string;
    errorHash?: string;
    createdAt?: string;
    updatedAt?: string;
  };
  inboxDelivery?: {
    inboxEventId?: string;
    triggerId?: string;
    sourceType?: string;
    source?: string;
    eventType?: string;
    eventId?: string;
    correlationId?: string;
    cursor?: string;
    dedupeKey?: string;
    payloadHash?: string;
    payloadSizeBytes?: number;
    signatureState?: string;
    signatureDetails?: Record<string, unknown>;
    rawBodySha256?: string;
    rawBodySizeBytes?: number;
    rawContentType?: string;
    rawHeaderNames?: string[];
    state?: string;
    deliveryCount?: number;
    triggerEventId?: string;
    runId?: string;
    failureCode?: string;
    receivedAt?: string;
    updatedAt?: string;
    deadLetteredAt?: string;
  };
};
