configfile: "run-config.json"

OUTPUT_REPORT = config["outputs"]["report"]
OUTPUT_SUMMARY = config["outputs"]["summary"]
OUTPUT_RAW_LOG = config["outputs"]["raw_log"]


rule all:
    input:
        report=OUTPUT_REPORT,
        summary=OUTPUT_SUMMARY,
        raw_log=OUTPUT_RAW_LOG,


rule generate_outputs:
    output:
        report=OUTPUT_REPORT,
        summary=OUTPUT_SUMMARY,
        raw_log=OUTPUT_RAW_LOG,
    conda:
        "envs/base.yaml"
    script:
        "scripts/generate_outputs.py"
